version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: fullstack_auth_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
      - ~/mongod.conf:/etc/mongod.conf
